// packages/vue/src/components/DiscordMessages.vue
<template>
	<div
		class="discord-messages"
		:class="{ 'discord-compact-mode': layout.compact, 'discord-light-theme': layout.light }"
	>
		<slot></slot>
	</div>
</template>

<script lang="ts">
import { defineComponent, provide, toRefs } from 'vue'
import { resolveOptions } from '../options'

export default defineComponent({
	name: 'DiscordMessages',
	props: {
		compactMode: {
			type: Boolean,
			'default': null,
		},
		lightTheme: {
			type: Boolean,
			'default': null,
		},
	},
	setup(props) {
		const options = resolveOptions()
		const { compactMode, lightTheme } = toRefs(props)

		const layout = {
			compact: compactMode?.value === true || (options.defaultMode === 'compact' && compactMode?.value !== false),
			light: lightTheme?.value === true || (options.defaultTheme === 'light' && lightTheme?.value !== false),
		}

		provide('compactMode', layout.compact)

		return {
			layout,
		}
	},
})
</script>

<style src="@pycord/discord-message-components-core/dist/styles/discord-messages.css"></style>

// packages/react/src/components/DiscordMessages.tsx
import React, { Children, PropsWithChildren, ReactElement, cloneElement, useContext } from 'react'
import DiscordDefaultOptions, { DiscordMessageOptions } from '../context/DiscordDefaultOptions'
import DiscordOptionsContext from '../context/DiscordOptionsContext'
import '@pycord/discord-message-components-core/dist/styles/discord-messages.css'

export type DiscordMessagesProps = PropsWithChildren<{
	compactMode?: boolean
	lightTheme?: boolean
}>

export default function DiscordMessages({ children, compactMode, lightTheme }: DiscordMessagesProps): ReactElement {
	const options: DiscordMessageOptions = useContext(DiscordOptionsContext) ?? DiscordDefaultOptions

	compactMode = compactMode === true || (options.defaultMode === 'compact' && compactMode !== false)
	lightTheme = lightTheme === true || (options.defaultTheme === 'light' && lightTheme !== false)

	let classes = 'discord-messages'
	if (compactMode) classes += ' discord-compact-mode'
	if (lightTheme) classes += ' discord-light-theme'

	const messages = Children.map((children as ReactElement[]), (child: ReactElement, index: number): ReactElement => {
		return cloneElement(child, { compactMode, key: index })
	})

	return (
		<div className={classes}>
			{messages}
		</div>
	)
}
