// packages/vue/src/components/DiscordMention.vue
<template>
	<span ref="root" class="discord-mention" :style="colorStyle">
		{{ mentionCharacter }}<slot>{{ defaultContent }}</slot>
	</span>
</template>

<script lang="ts">
import { computed, defineComponent, onBeforeUnmount, onMounted, ref, toRefs } from 'vue'
import { util } from '@pycord/discord-message-components-core'
import { resolveOptions } from '../options'

export default defineComponent({
	name: 'DiscordMention',
	props: {
		highlight: Boolean,
		profile: String,
		roleColor: String,
		type: {
			type: String,
			'default': 'user',
		},
	},
	setup(props) {
		const options = resolveOptions()
		const root = ref<HTMLSpanElement>()
		const { profile: profileKey, roleColor, type } = toRefs(props)
		const profile = ref(!profileKey?.value ? {} : options.profiles?.[profileKey?.value] ?? {})
		const color = ref(roleColor?.value ?? profile?.value?.roleColor)

		const hovering = ref(false)
		const setHoverColor = () => hovering.value = true
		const resetHoverColor = () => hovering.value = false

		const colors = {
			background: util.parseColorToRgba(color?.value, 0.1),
			hover: util.parseColorToRgba(color?.value, 0.3),
		}

		const colorStyle = computed(() => {
			return color?.value && type.value === 'role'
				? {
					color: color.value,
					'background-color': hovering.value ? colors.hover : colors.background,
				}
				: {}
		})

		onMounted(() => {
			if (color?.value && type?.value === 'role') {
				root?.value?.addEventListener('mouseenter', setHoverColor)
				root?.value?.addEventListener('mouseout', resetHoverColor)
			}
		})

		onBeforeUnmount(() => {
			root?.value?.removeEventListener('mouseenter', setHoverColor)
			root?.value?.removeEventListener('mouseout', resetHoverColor)
		})

		const defaultContent = computed(() => {
			return type.value === 'user' && profile?.value?.author
				? profile?.value.author
				: type.value === 'channel'
					? type.value
					: type.value.charAt(0).toUpperCase() + type.value.slice(1)
		})

		const mentionCharacter = computed(() => type.value === 'channel' ? '#' : '@')

		return {
			root,
			colorStyle,
			defaultContent,
			mentionCharacter,
		}
	},
})
</script>

<style src="@pycord/discord-message-components-core/dist/styles/discord-mention.css"></style>

// packages/react/src/components/DiscordMention.tsx
import React, { PropsWithChildren, ReactElement, useContext, useEffect, useRef, useState } from 'react'
import { util } from '@pycord/discord-message-components-core'
import DiscordDefaultOptions, { DiscordMessageOptions, Profile } from '../context/DiscordDefaultOptions'
import DiscordOptionsContext from '../context/DiscordOptionsContext'
import '@pycord/discord-message-components-core/dist/styles/discord-mention.css'

export type DiscordMentionProps = PropsWithChildren<{
	highlight?: boolean
	profile?: string
	roleColor?: string
	type?: string
}>

export default function DiscordMention({ children, roleColor, profile: profileKey, type = 'user' }: DiscordMentionProps): ReactElement {
	const options: DiscordMessageOptions = useContext(DiscordOptionsContext) ?? DiscordDefaultOptions
	const root = useRef<HTMLSpanElement>(null)
	const profile: Profile = !profileKey ? {} : options.profiles?.[profileKey] ?? {}
	const color = roleColor ?? profile?.roleColor

	const [hovering, setHovering] = useState(false)
	const setHoverColor = () => setHovering(true)
	const resetHoverColor = () => setHovering(false)

	const colors = {
		background: util.parseColorToRgba(color, 0.1),
		hover: util.parseColorToRgba(color, 0.3),
	}

	const colorStyle = color && type === 'role'
		? { color, backgroundColor: hovering ? colors.hover : colors.background }
		: {}

	useEffect(() => {
		if (color && type === 'role') {
			root?.current?.addEventListener('mouseenter', setHoverColor)
			root?.current?.addEventListener('mouseout', resetHoverColor)
		}

		return () => {
			root?.current?.removeEventListener('mouseenter', setHoverColor)
			root?.current?.removeEventListener('mouseout', resetHoverColor)
		}
	}, [root, color, type])

	const defaultContent = children && children !== ''
		? children
		: type === 'user' && profile?.author
			? profile.author
			: type === 'channel'
				? type
				: type.charAt(0).toUpperCase() + type.slice(1)

	const mentionCharacter = type === 'channel' ? '#' : '@'

	return (
		<span ref={root} className="discord-mention" style={colorStyle}>
			{mentionCharacter}{defaultContent}
		</span>
	)
}
