// packages/vue/src/components/DiscordButton.vue
<template>
	<a
		v-if="type === 'link' && url && !disabled"
		class="discord-button discord-button-link"
		:href="url"
		target="_blank"
		rel="noopener noreferrer"
	>
		<img v-if="image" class="discord-button-emoji" :src="image" alt="" />
		<slot></slot>
		<outbound-link-icon />
	</a>
	<button
		v-else
		class="discord-button"
		:class="[`discord-button-${type}`, disabled ? 'discord-button-disabled' : '']"
		:disabled="disabled"
	>
		<img v-if="image" class="discord-button-emoji" :src="image" alt="" />
		<slot></slot>
		<outbound-link-icon v-if="type ==='link'" />
	</button>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import OutboundLinkIcon from './OutboundLinkIcon.vue'

export default defineComponent({
	name: 'DiscordButton',
	components: {
		OutboundLinkIcon,
	},
	props: {
		disabled: Boolean,
		image: String,
		type: {
			type: String,
			'default': 'primary',
		},
		url: String,
	},
})
</script>

<style src="@pycord/discord-message-components-core/dist/styles/discord-button.css"></style>

// packages/react/src/components/DiscordButton.tsx
import React, { ReactElement } from 'react'
import { PropsWithSlot } from '../util'
import OutboundLinkIcon from './OutboundLinkIcon'
import '@pycord/discord-message-components-core/dist/styles/discord-button.css'
import Twemoji from 'react-twemoji'

export type DiscordButtonProps = {
	disabled?: boolean
	image?: string
	type?: string
	url?: string
	emoji?: string
} & PropsWithSlot

export default function DiscordButton({ children, disabled, image, type = 'primary', url, emoji }: DiscordButtonProps): ReactElement {
	return type === 'link' && url && !disabled
		? (
			<a
				className="discord-button discord-button-link"
				href={url}
				target="_blank"
				rel="noopener noreferrer"
			>
				{image && <img className="discord-button-emoji" src={image} alt="" />}
				{emoji && <Twemoji options={{ className: 'discord-button-emoji' }}>{emoji}</Twemoji>}
				{children}
				<OutboundLinkIcon />
			</a>
		)
		: (
			<button
				className={`discord-button discord-button-${type}${disabled ? ' discord-button-disabled' : ''}`}
				disabled={disabled}
			>
				{image && <img className="discord-button-emoji" src={image} alt="" />}
				{emoji && <Twemoji options={{ className: 'discord-button-emoji' }}>{emoji}</Twemoji>}
				{children}
				{type === 'link' && <OutboundLinkIcon />}
			</button>
		)
}
