// packages/react/src/components/DiscordReaction.tsx
import React, { ReactElement } from 'react'
import '@pycord/discord-message-components-core/dist/styles/discord-reaction.css'

export type DiscordReactionProps = {
	active?: boolean
	count?: number
	image: string
	name?: string
}

export default function DiscordReaction({ active, count = 1, image, name }: DiscordReactionProps): ReactElement {
	let classes = 'discord-reaction'
	if (active) classes += ' discord-reaction-active'

	return (
		<div className={classes} title={name}>
			<img className="discord-reaction-emoji" src={image} alt={name} />
			<span className="discord-reaction-count">{count}</span>
		</div>
	)
}

// packages/vue/src/components/DiscordReaction.vue
<template>
	<div class="discord-reaction" :class="{ 'discord-reaction-active': active }" :title="name">
		<img class="discord-reaction-emoji" :src="image" :alt="name" />
		<span class="discord-reaction-count">{{ count }}</span>
	</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
	name: 'DiscordReaction',
	props: {
		active: Boolean,
		count: {
			type: Number,
			'default': 1,
		},
		image: {
			type: String,
			required: true,
		},
		name: String,
	},
})
</script>

<style src="@pycord/discord-message-components-core/dist/styles/discord-reaction.css"></style>
