// packages/react/src/components/DiscordButtons.tsx
import React, { ReactElement } from 'react'
import { PropsWithSlot } from '../util'
import '@pycord/discord-message-components-core/dist/styles/discord-buttons.css'

export default function DiscordButtons({ children }: PropsWithSlot): ReactElement {
	return (
		<div className="discord-buttons">
			{children}
		</div>
	)
}

// packages/vue/src/components/DiscordButtons.vue
<template>
	<div class="discord-buttons">
		<slot></slot>
	</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
	name: 'DiscordButtons',
})
</script>

<style src="@pycord/discord-message-components-core/dist/styles/discord-buttons.css"></style>
